# Generated by Django 5.1 on 2025-11-12 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('bibliografia', models.TextField()),
                ('paginaweb', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferenciasgenero', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('editorialid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreeditorial', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('emailcontacto', models.EmailField(max_length=255)),
                ('sitioweb', models.URLField(blank=True, max_length=255, null=True)),
                ('paisorigen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombreeditorial'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libroid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('anioPublicacion', models.IntegerField()),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil'), ('POE', 'Poesía'), ('DRA', 'Drama')], max_length=100)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(default=django.utils.timezone.now)),
                ('montototal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodopago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('DIGITAL', 'Pago Digital')], max_length=50)),
                ('estadoVenta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('EN_PROCESO', 'En Proceso')], default='PENDIENTE', max_length=50)),
                ('descuentoAplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fechaventa'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleDeLaVentaid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Libreria.libro')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Libreria.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
